### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by wvengen**
First of all, congrats with the release of 14.0!

When playing around with the image, it seems to work fine most of the time.
These changes were needed to make it work smoothly in these cases as well.

How is the process for these changes - do I need to update the changelog? Will this result in a rebuild of the published appliance, or is that a manual step taking some effort?

### CODE REVIEW

**Comment by JedMeister** [comment]
Happy to merge these but just wanted to know if they are show stoppers or just improvements?

**Comment by wvengen** [comment]
Thanks for looking! They can be showstoppers (e.g. the background worker not starting).

**Comment by wvengen** [comment]
Thanks! I now see that I also have commit access, next time I'd be happy to merge myself.
What would be needed to trigger a rebuild? Update the changelog? (Perhaps there are docs on this, but I haven't found them yet.)

**Comment by JedMeister** [comment]
Do you? TBH that's a bit weird... No offence but you shouldn't and according to the settings only Alon, Liraz and myself have commit access...!?

Unfortunately we don't have an automated rebuild trigger. All the building is manually triggered. We have automated quite a bit of the behind the scenes stuff but it is still incomplete. Automation of builds is something we have been wanting to add for some time but other stuff keeps getting in the way!

Also we are planning to make some significant changes to how the v15.0 images are built (more on that at a later date) so we haven't made further steps towards automation (that may need to be re-written anyway).

So short answer is I just need to do the rebuild! As there is a bit of an overhead on (re)building we only really want to be doing batch (re)builds. But as we still haven't quite finished with the optimised builds the overhead is lower at this point. We also have a couple of other appliances that need re-building so it's all good...

**Comment by wvengen** [comment]
Hmm, I don't have access now. Perhaps I misread the Github UI. Sorry. (And I totally understand the restrictions!)

I see, thanks for explaining. I can wait - and perhaps I'll sneak in another PR to update the Foodsoft version. Or do we stick with one (major.minor) version for appliance software for a major TKL release?

**Comment by JedMeister** [comment]
Sorry on slow reply. I'm about to do the rebuild so this is it for v14.0. 

Re updates; there is no issue with newer version for v14.1 but it may make sense to leave that until closer to the date rather than have to keep updating over and over. I'll leave that to your judgement.

**Comment by wvengen** [comment]
No problem. Thanks, I'll leave it for now and bump versions when v14.1 is due (after testing, of course).

**Comment by JedMeister** [comment]
Cool. I'll plan to give you a ping when we start looking at v14.1 then. :smile:

**Comment by wvengen** [comment]
Thanks :+1:

**Pull request merged**
